const funcionarios = [
  {
    nome: "Marco Tulio",
    linkedin: "https://media.licdn.com/dms/image/v2/C4D03AQG0qEHl5JMhpQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1624281151045?e=1757548800&v=beta&t=pjMvGyIBNdAopXqOycgoF6CtSHM2g55aonK9fd2tOp8",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Joao Vitor Cavalcanti Duarte",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQGiPd0zLtiPsA/profile-displayphoto-shrink_200_200/B4DZYnUiV9G4AY-/0/1744416418844?e=1757548800&v=beta&t=2KQLGRpjz9VM2bswJv8SntnqKD_PoCPY3Cu7R6CpF-4",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Francisco Ferreira",
    linkedin: "https://media.licdn.com/dms/image/v2/C4E03AQGHMEz_IZh1ig/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1624042117804?e=1757548800&v=beta&t=u0kbclcsXELOjo68uS6o5flfrLJYfrhd8W38RFKoTd8",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Letícia Rodrigues França",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQF04Ym6GTAusQ/profile-displayphoto-shrink_200_200/B4DZTZGYVzGcAY-/0/1738809117524?e=1757548800&v=beta&t=teN4OBOwvTqIq15dC_i54oq4cx_SzqNBM6R_VtJPrAY",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Lygia Paloma Calado Ruffo",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQFgojFApwA-ZQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1695118675070?e=1757548800&v=beta&t=409VMBjjYJOsKZ9WXOoP2E44LHeP7jLBtrIZ8lJ9Ep8",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Paula Eduarda Vasconcelos de Oliveira",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQEov7XWM-hvQw/profile-displayphoto-shrink_200_200/B4DZRiFmJDGkAc-/0/1736812422836?e=1757548800&v=beta&t=SaHX3sfAtPUcb-m6wqc2ZAzLrDfR_xWC5OCAgkV2K1I",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Luiz Felipe de Souza",
    linkedin: "https://media.licdn.com/dms/image/v2/C4D03AQHnupdvxBGydw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1663686779535?e=1757548800&v=beta&t=rfEuwsIYqx_rJM0ORRAsEYUOVPYpIbAnwLN-IdTiutY",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Julia Pessoa Souza",
    linkedin: "https://media.licdn.com/dms/image/v2/C4D03AQHL44U2p3M93w/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1636386064160?e=1757548800&v=beta&t=jIIjdYzAaNngnk38IdbwLbI6WfiyKjl8E-UZVctAitE",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "João Emanuel dos Santos Costa",
    linkedin: "https://media.licdn.com/dms/image/v2/C4E03AQEfVrfccQ6Iwg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1656774926210?e=1757548800&v=beta&t=bsWU-M9fQ8aHsIn3XIBETftauJ1FNL1Yp4KSI_zSSd4",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "João Vitor Couto Casas Novas",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQFRxU14u2zPZQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1695305563503?e=1757548800&v=beta&t=2hbAQ_GZxDhOuEe2RDsAzl6bM2ANORjTgOXuPeVwdkE",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Gustavo Henrique Guilherme ",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQEnjJu2qsAEqA/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1670712034689?e=1757548800&v=beta&t=b91PVt9k3OVfUC20aMMB4ghMX_bkFnYinbomFxaWEFQ",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Matheus Mello de Brito ",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQFobjUktlfMiw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1724721270976?e=1757548800&v=beta&t=7jMFeM19ebtmZHSlwDagamr_UB8XePMXQwULoDMBQ9U",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Gabriel Benazzi Gonçalves",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQHLkdY-Tj8eGw/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1696421914257?e=1757548800&v=beta&t=Xn209fmgUSpxPDv_YBNh93mMGLqAaJMYJFyPmkS9xk8",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Arthur Andrade de Padua Carvalho",
    linkedin: "https://media.licdn.com/dms/image/v2/D4E03AQH8FNm0SYtqjg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1730165815728?e=1757548800&v=beta&t=3McNDPlU8RZCWbjfjpHhGfMRrJQyB4o55YSBcFHBJkU",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Octavio Henrique",
    linkedin: "https://media.licdn.com/dms/image/v2/D4E03AQHPU4Zm71BfyA/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1699576620483?e=1757548800&v=beta&t=u1XFwu269rH6fLCbnCB7uD6Xg6sxF_OyY64A6dsBfLQ",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Wesley Santos Dutra",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQGq3LvHzhh34Q/profile-displayphoto-shrink_200_200/B4DZXIdxC.HIAY-/0/1742825002095?e=1757548800&v=beta&t=tRDaBumqYxpR6jPWx-_RJkgl0fKvE6VEu4PRszzt8GY",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Pethrus Doti Modesto",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQHGlyvwsCd_Qg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1692388511843?e=1757548800&v=beta&t=CeM7gwiGQf9q4StDNhIUBB6zDfBzjC7CVoq19sARZHw",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Lucas Silveira",
    linkedin: "https://media.licdn.com/dms/image/v2/C4D03AQHUwzAjqvaI4w/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1594669961338?e=1757548800&v=beta&t=UXdHAe51VvaWGwqJg62sAA9m9fuHmz44_weycM3mrn4",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Cithia Dahyane",
    linkedin: "https://media.licdn.com/dms/image/v2/C4D03AQEMDrzgFFJpGw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1602039104953?e=1758153600&v=beta&t=2SSTrHfZJZLsjXZrY7ZsH70jpZzRBx3Zcxk-iYIh28U",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Felipe José Pereira Ferreira",
    linkedin: "https://media.licdn.com/dms/image/v2/C4E03AQHcAvPZ6F8c0A/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1643379043705?e=1757548800&v=beta&t=jUABpp9zw53v6WT3Vs7at00IfoJBUrs04MaSDAQy9Ns",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  },
  {
    nome: "Matheus Duarte Assis",
    linkedin: "https://media.licdn.com/dms/image/v2/D4D03AQG8Ys7EDjS0zQ/profile-displayphoto-shrink_200_200/B4DZTLhve3HYAo-/0/1738581409184?e=1757548800&v=beta&t=rpYSX0R5_Sn06aEOUK0Ljwt_37aeOurzcs4BvbLSP5c",
    hard: {
      
      "Ciclo V": 7,
      "Sistemas embarcados": 9,
      "Power BI": 6,
      "Excel Avançado": 8,
      "Arquitetura CAN LIN": 7,
      "Eletrônica Veicular": 9,
      "ASPICE": 6,
      "ISO 26262": 7,
      "Vector CANape": 7,
      "Vector CANoe": 9,
      "Vector CANalyzer": 6,
      "CAPL": 7,
      "Metodologias de diagnose (Ishikawa, ACR e Kanban)": 8,
      "Automotive Virtualization (SiL, HiL, MiL, etc.)": 7,
      "AUTOSAR": 9,
      "CANdela": 6,
      "Matlab": 7,
      "Leitura e Interpretação de Esquema Elétrico": 7,
      "Python": 7,
      "IPG Carmaker": 7,
      "Vehicle Dinamics": 7,  
    },
    processos: {
      "Gestão de Budget": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Validação de linha de produção": 5,
      "Rampup de Produção": 7,
      "Nomeação de Fornecedor": 8,
      "Criação de Part Number": 8,
      "Gestão de Documentação Técnica": 7,
      "Gestão de Alteração de Projeto": 8,
      "Qualidade de fornecedor": 6,
      "Rampup de Produção": 7
      },
    soft: {
      "Proatividade": 6,
      "Vontade de Aprender": 7,
      "Comunicação": 8,
      "Trabalho em equipe": 7,
      "Organização": 7,
      "Capacidade de Síntese": 9,
      "Aptidão para Decisão": 6,
      "Gestão de Risco": 7,
      "Resiliência": 8,
      "Inteligência Emocional": 7,
      "Influência": 9,
      "Autonomia": 6,
      "Habilidade de Liderança": 7,
      "Feedback do Cliente": 8,
      "Criatividade": 7,
    }
  }
];
